apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cart-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cart-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cart-api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "cart-api.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["./app"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            - secretRef:
                name: {{ .Values.secretName }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
