apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-db-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
