apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.postgres.name }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.labels.app }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
          volumeMounts:
            - name: {{ .Values.postgres.storage.volumeName }}
              mountPath: {{ .Values.postgres.storage.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgres.storage.volumeName }}
      spec:
        accessModes:
          - {{ .Values.postgres.storage.accessMode }}
        storageClassName: {{ .Values.postgres.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
