apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-api-config
  namespace: test
data:
  HTTP_PORT: "3000"
  LOG_LEVEL: "debug"

  DB_HOST: cart-db
  DB_PORT: "5432"
  DB_NAME: cart-api-db
  DB_SSLMODE: disable
